name: 'Terraform'

on: push

jobs:
  terraform:
    name: 'Terraform Init'
    runs-on: ubuntu-latest
    environment: production

    steps:
     - name: Terraform Init
       run: terraform init
       
     - name: Checkout
       uses: actions/checkout@v4
      
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1
  


