name: Terraform TODOAPP Infra Pipeline
on: push
jobs:
  terraform:
    name: Terraform Init
    runs-on: ubuntu-latest

    steps:
    
      - name: Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./Todo_Infra/Environment
/dev/
      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Todo_Infra/Environment
/dev/



